### ISSUE TITLE
[Minecraft 1.18.2] [ProbeJS 4.0.0 fix4] [ProbeJS Extension 1.0] A few problems.

### ISSUE THREAD

**Issue by thelyric27** [Prunoideae/ProbeJS-Extension#3]
So, a couple things. To start with, I noticed that the ProbeJS mod isn't generating a config file in .minecraft/kubejs/config/ ...

So that's causing my other issue, the ProbeJS VSCode extension isn't activating because it can't find said config.

```
2024-03-27 03:11:29.409 [error] Activating extension Prunoideae.probejs failed due to an error:
2024-03-27 03:11:29.409 [error] Error: ENOENT: no such file or directory, open '/home/lyric/Apps/Prism Launcher/instances/CC Coding Instance/.minecraft/kubejs/config/probejs.json'
	at Object.openSync (node:fs:605:3)
	at Object.func [as openSync] (node:electron/js2c/node_init:2:2107)
	at Object.readFileSync (node:fs:473:35)
	at Object.<anonymous> (node:electron/js2c/node_init:2:9456)
	at ri (/home/lyric/.vscode/extensions/prunoideae.probejs-0.1.0/out/extension.js:87:2054)
	at j.ib (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:13251)
	at j.hb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:12964)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:11089
	at async u.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
	at async u.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
	at async u.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)
```

Here's a latest.log and the debug.log

https://mclo.gs/V7TgebT

https://mclo.gs/Lt4hFiD

What can I do here? Not sure what could be going wrong.

**Comment by Prunoideae** [comment]
It's because ProbeJS VSCode Extension is only for 1.19.2+, ProbeJS itself should run without problem alone in 1.18.2.
